### ISSUE TITLE
Internal ELB Not needed

### ISSUE THREAD

**Issue by stevesloka** [heptio/aws-quickstart#159]
Currently, the quickstart creates an internal ELB for the control plane which is not required in a non-HA setup. I don't see a reason to require this but wanted to check and verify. Not having would save on overall costs for the cluster.

**Comment by chuckha** [comment]
@stevesloka are you suggesting that we expose the api server directly to the world with a public ip address instead of an elb in the public subnet pointing to the private subnet?

**Comment by stevesloka** [comment]
No, my suggestion was to remove the ELB completely. If you don't have an HA control plane, all kubelets can use the IP of the control plane machine. The control plane machine gets a public IP and the ELB is not used.  I may be misunderstanding the architecture of how it's implemented though.

**Comment by chuckha** [comment]
you're right the kubelets could use a public or private ip since they are in the same network and don't have to use the elb address. The problem is that the elb isn't totally internal and that's what we use for external traffic to the control plane.

For instance, here is my kubeconfig for a quickstart cluster:

```
 salazar:aws-quickstart cha$ cat ~/.kube/test
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *snip*
    server: https://my-k8s-cl-apiloadb-128xrd0coyrnm-240200060.us-west-2.elb.amazonaws.com
```
