### ISSUE TITLE
Services with `externalTrafficPolicy: Local` seem not to work

### ISSUE THREAD

**Issue by dkalintsev** [heptio/aws-quickstart#173]
If I create a `NodePort` Service with `externalTrafficPolicy: Local`, I can't connect to it on NODE_IP:NodePort. If the Service is patched to set `externalTrafficPolicy` to `Cluster`, connectivity works.

Using a QuickStart deployed with all defaults (CoreDNS / Calico).

Example Deployment + Service that doesn't work unless I remove `externalTrafficPolicy`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
        #
        # There isn't anything listeing on 443; included just as an example
        #
        - containerPort: 443
          name: https
        #
        # This will change the page nginx serves to show container's hostname
        #
        command: ["/bin/bash"]
        args: ["-c", "printenv HOSTNAME > /usr/share/nginx/html/index.html && nginx -g \"daemon off;\""]
      #
      # This Anti-Affinity rule will prevent K8s from scheduing
      # more than pod on the same node, so that we can provide
      # proper session persistence and pod health checking.
      #
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - my-nginx
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    run: my-nginx-svc
spec:
  # Prevent this Service from sending traffic to other nodes
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    run: my-nginx
  type: NodePort
```

Example session:

```
kubectl get pods -o wide
NAME                       READY     STATUS    RESTARTS   AGE       IP               NODE
my-nginx-5b44bffd9-mx654   1/1       Running   0          14m       192.168.89.195   ip-10-0-0-168.ap-southeast-2.compute.internal

kubectl get svc -o wide
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
kubernetes         ClusterIP   10.96.0.1       <none>        443/TCP        1h        <none>
my-nginx-service   NodePort    10.111.158.65   <none>        80:32459/TCP   14m       run=my-nginx

```

From Bastion host, after adjusting the SG applied to nodes to allow appropriate connectivity:

```
ubuntu@ip-10-0-128-5:~$ curl http://10.0.0.168:32459
^C
```

```
kubectl patch svc my-nginx-service -p '{"spec":{"externalTrafficPolicy":"Cluster"}}'
service "my-nginx-service" patched
```

```
ubuntu@ip-10-0-128-5:~$ curl http://10.0.0.168:32459
my-nginx-5b44bffd9-mx654
```

```
kubectl patch svc my-nginx-service -p '{"spec":{"externalTrafficPolicy":"Local"}}'
service "my-nginx-service" patched
```

```
ubuntu@ip-10-0-128-5:~$ curl http://10.0.0.168:32459
^C
```
