### ISSUE TITLE
Allow service accounts in the pods to list stuff.

### ISSUE THREAD

**Issue by jayunit100** [heptio/aws-quickstart#75]
**Problem**

Default Helm wants to be able to list configmaps in various namespaces, but looks like svc accounts lock that down in the default heptio quickstart.

**Solution**

Somehow make the default service accounts capable of listing all API objects.

**Details**

- helm default tries to run in  kube-system (I understand why that might be locked down).  That works out of the box on minikube.
- To workaround, I tried useing `tiler-

```
ubuntu@ip-10-0-22-242:/opt$ helm-exec list --tiller-namespace=default Error: User "system:serviceaccount:default:default" cannot list configmaps in the namespace "default". (get configmaps)
```

Is the quickstart doing something special to lockdown service account ACLs ?  If so, can we loosen up the defaults?  

Users should be able to run helm out of the box, in there shiny new heptio clusters :) 

cc @timothysc not sure who else to CC ...

```
ubuntu@ip-10-0-22-242:/opt$ kubectl  logs tiller-deploy-3937166581-7c87m
[main] 2017/07/14 17:07:07 Starting Tiller v2.5.0 (tls=false)
[main] 2017/07/14 17:07:07 GRPC listening on :44134
[main] 2017/07/14 17:07:07 Probes listening on :44135
[main] 2017/07/14 17:07:07 Storage driver is ConfigMap
[storage] 2017/07/14 18:12:20 listing all releases with filter
[storage/driver] 2017/07/14 18:12:20 list: failed to list: User "system:serviceaccount:default:default" cannot list configmaps in the namespace "default". (get configmaps)
```

**Comment by jayunit100** [comment]
Actually, https://github.com/kubernetes/dashboard/issues/1800 indicates this is a 1.6 kube-adm idiosyncracy/bug/securityfeature . 

Either way some docs or maybe having installer smooth it over w/ a few `create clusterrolebinding`
commands might be a good route forward.

**Comment by chuckha** [comment]
@jayunit100 For helm I create a helm service account with admin access and then use `helm init --service-account helm`

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: kube-system
```

I don't like to give the default service account admin level access, but I think adding RBAC to the quickstart is out of scope.

Do you think a solution would be to document that the quickstart does not include any RBAC roles/bindings?
